### ISSUE TITLE
failed to volumes the ossec.conf

### ISSUE THREAD

**Issue by yehaotong** [wazuh/wazuh-docker#493] opened 2021-08-09 09:04 UTC
when I use the wazuh-manager and try to volumes the ossec.conf,it always failed(filed in init the etc/cont-init.d/2-manager),what is the problem ? I volumes the path is:/var/ossec/etc/ossec.conf,is that make me failed? ossec.conf do not need to put in /var/ossec/etc?

**Comment by rauldpm** [comment] 2021-08-11 17:58
Hello @yehaotong 

What version of wazuh-docker are you using? If you can, please describe the process you are doing until you reach that error.

In 4.0 and 4.1 the `/var/ossec/etc` folder is by default on the `ossec_etc` volume, you can check this in the docker compose file and in the documentation: https://documentation.wazuh.com/current/docker/container-usage.html

In the case of lower versions such as 3.13.3, this is not the case, the docker compose file does not specify any volume, but if it is done in Wazuh's own Dockerfile, in this case, the folder is not `/var/ossec/etc` but `/var/ossec/data`

You can see the volumes with the command `docker volume ls`
You can check where these volumes are mounted with the command  `docker volume inspect VOLUME_NAME`  through the `Mountpoint` field

**Comment by yehaotong** [comment] 2021-08-12 05:25
> 你好@yehaotong
> 
> 您使用的是什么版本的 wazuh-docker？如果可以，请描述您在遇到该错误之前正在执行的过程。
> 
> 在 4.0 和 4.1 中，`/var/ossec/etc`文件夹默认位于`ossec_etc`卷上，您可以在 docker compose 文件和文档中查看：[https](https://documentation.wazuh.com/current/docker/container-usage.html) : [//documentation.wazuh.com/current/docker/container-usage.html](https://documentation.wazuh.com/current/docker/container-usage.html)
> 
> 在3.13.3等低版本的情况下，就不是这样了，docker compose文件没有指定任何卷，但是如果是在Wazuh自己的Dockerfile中做的，在这种情况下，文件夹不是`/var/ossec/etc`但是`/var/ossec/data`
> 
> 您可以使用命令查看卷`docker volume ls`
> 您可以`docker volume inspect VOLUME_NAME` 通过该`Mountpoint`字段使用命令检查这些卷的安装位置

I use the version is the latest:4.1.5,and my docker file is :
FROM wazuh/wazuh-odfe:4.1.5

**Comment by yehaotong** [comment] 2021-08-12 05:32
> 你好@yehaotong
> 
> 您使用的是什么版本的 wazuh-docker？如果可以，请描述您在遇到该错误之前正在执行的过程。
> 
> 在 4.0 和 4.1 中，`/var/ossec/etc`文件夹默认位于`ossec_etc`卷上，您可以在 docker compose 文件和文档中查看：[https](https://documentation.wazuh.com/current/docker/container-usage.html) : [//documentation.wazuh.com/current/docker/container-usage.html](https://documentation.wazuh.com/current/docker/container-usage.html)
> 
> 在3.13.3等低版本的情况下，就不是这样了，docker compose文件没有指定任何卷，但是如果是在Wazuh自己的Dockerfile中做的，在这种情况下，文件夹不是`/var/ossec/etc`但是`/var/ossec/data`
> 
> 您可以使用命令查看卷`docker volume ls`
> 您可以`docker volume inspect VOLUME_NAME` 通过该`Mountpoint`字段使用命令检查这些卷的安装位置

I use the version is the latest:4.1.5,and my docker file is :
FROM wazuh/wazuh-odfe:4.1.5
COPY config/ossec.conf /var/ossec/etc/ossec.conf
I copy directly into the dockerfile in this way, which is the same error as when I use docker run - V config / ossec. Conf: / var / ossec / etc / ossec. Conf A file could not be found while loading the 2-manage script
I

**Comment by rauldpm** [comment] 2021-08-12 17:22
Hello @yehaotong 

Sorry, I still don't know the purpose you want to achieve with this, do you want to have the ossec.conf file mounted on a volume permanently? Do you want to mount it to update the ossec.conf configuration with one that you have made?

What is the reason to use that Dockerfile? Could you share the Dockerfile you are using? I am trying to reproduce your problem but i can't.

Regarding 2-manager, this script is used for file migration as its header says:

```
##############################################################################
# Migration sequence
# Detect if there is a mounted volume on /wazuh-migration and copy the data
# to /var/ossec, finally it will create a flag ".migration-completed" inside
# the mounted volume
##############################################################################
```

This process is done when upgrading the wazuh version to avoid data loss from `3.x` to `4.x`, so if you are using `4.1.5`, this should not be involved. Link to this file: https://github.com/wazuh/wazuh-docker/blob/v4.1.5/wazuh-odfe/config/etc/cont-init.d/2-manager

From what I see from the `COPY` of the Dockerfile, if what you want is to modify the `ossec.conf` file it is not necessary to use a `Dockerfile`, you can access the container in the following way:

- First, you need the service name that you want to access, you can see it in the `docker-compose.yml` file, currently the services are:

  - wazuh
  - elasticsearch
  - kibana

- Second, you can access to the container (per example: wazuh) with:

`docker-compose exec wazuh /bin/bash`

![image](https://user-images.githubusercontent.com/14913942/129240253-d3881a82-6070-444a-812e-e5d24386c83e.png)

Another way is to directly copy the file with "`docker cp`", for this you need to know first the "`CONTAINER ID`", you can find it with:

`docker ps`

![image](https://user-images.githubusercontent.com/14913942/129240387-b7a6cce9-5669-4146-a7b4-01e75c6de5ea.png)

Once you have the "`CONTAINER ID`", you can copy a file (in this example `ossec.conf` is available in the `myconfig` folder) in the form:

`docker cp myconfig/ossec.conf "CONTAINER ID":/var/ossec/etc/ossec.conf`

If this is not useful or is not what you need, please, I would need to know what steps you have followed to find that error and if you explain to me what you want to do, maybe I can give you a step-by-step solution if possible.

Here are a link to the wazuh documentation on how to use wazuh-docker https://documentation.wazuh.com/current/docker/index.html

**Comment by yehaotong** [comment] 2021-08-14 05:36
通用领域
生物医药
我想做到的就是就是把这个ossec.conf挂载出来而不用在你们原生的dockerfile里cop进去，我的dockerfile文件就是这样：
FROM wazuh/wazuh-odfe:4.1.5
COPY config/ossec.conf /var/ossec/etc/ossec.conf
这是一开始的做法，我想直接从外部cp进去，但失败了，所以我改成直接run你们的wazuh-ofde然后加上挂载参数-v ossec.conf，但还是失败了，报错的日志与我cp进去相同都是2-manager脚本跑失败了
我想做到的就是就是把这个ossec.conf挂载出来而不用在你们原生的dockerfile里cop进去，我的dockerfile文件就是这样：
FROM wazuh/wazuh-odfe:4.1.5
COPY config/ossec.conf /var/ossec/etc/ossec.conf
这是一开始的做法，我想直接从外部cp进去，但失败了，所以我改成直接run你们的wazuh-ofde然后加上挂载参数-v ossec.conf，但还是失败了，报错的日志与我cp进去相同都是2-manager脚本跑失败了
What I want to do is to mount this ossec.conf instead of cop in your native dockerfile. My dockerfile is like this:

FROM wazuh/wazuh-odfe:4.1.5

COPY config/ossec.conf /var/ossec/etc/ossec.conf

This is the initial practice. I wanted to go in directly from the external CP, but it failed, so I changed to directly run your wazuh ofDe and add the mount parameter - V ossec.conf, but it still failed. The error log is the same as that of my CP. both 2-manager scripts failed

**Comment by rauldpm** [comment] 2021-08-17 19:27
Hello @yehaotong 

**Can you provide me with the specific error that appears in the terminal please?**

I have done a test with your Dockerfile, without using anything else from the wazuh-docker repository since it seems that you are not using anything from the repository, here it was my error, sorry, generally this repository is intended to be used in conjunction with other images as seen in `docker-compose.yml`

Keep in mind that the `wazuh/wazuh-odfe: 4.1.5` image has its own tools that are activated when running the built image, in this case, even if you copy the `ossec.conf` file in `/var/ossec/etc/ossec.conf`, in the `docker run` command you will see the error:

![image](https://user-images.githubusercontent.com/14913942/129787762-3764d93a-7d8d-4535-96db-1648c079a6ba.png)

To use an external configuration, either by copying it or using volumes, the path where you have to put the file is: `/wazuh-config-mount/etc/`, you can check this in the file `0-wazuh-init` : https://github.com/wazuh/wazuh-docker/blob/master/wazuh-odfe/config/etc/cont-init.d/0-wazuh-init

---

Here you can see how using a Dockerfile with the content

```
FROM wazuh/wazuh-odfe:4.1.5
COPY config/ossec.conf /var/ossec/etc/ossec.conf
```

I have been able, after doing a build and a run, to enter the container and verify that the file has been copied correctly without error.

![image](https://user-images.githubusercontent.com/14913942/129787395-507b379f-3152-4c9a-ba37-4515a1e632c0.png)


---

If instead of using COPY you use volumes, as you can see, also the specified file is passed to the container, but in this case, if you modify the file from outside it will also be modified in the container (since they are really the same).

![image](https://user-images.githubusercontent.com/14913942/129787415-4beb9b60-bbcb-4201-b3df-f46b2fccdd48.png)

Either way, here you can see how the error no longer appears by using the /wazuh-config-mount/etc/ path

![image](https://user-images.githubusercontent.com/14913942/129787543-beee560d-3653-4950-8173-bfe0d248ba2d.png)

**Comment by yehaotong** [comment] 2021-08-19 05:20
thanks for you advice，I will try to copy/volume  the path on /wazuh-config-mount/etc/ and test it ，thanks you aging.

**Comment by rauldpm** [comment] 2021-08-19 18:37
You're welcome, if you have any questions or problems, don't hesitate to ask!

**Comment by alberpilot** [comment] 2021-09-09 13:02
I procced to close this issue. Don't hesitate to open it again if necessary. 

Regards, 
Alberto R

**Closed by alberpilot** 2021-09-09 13:02 UTC
Labels: community, cicd-tracked
