### ISSUE TITLE
Wazuh API service stopped

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-docker#149] opened 2019-04-12 13:36 UTC
Hello team,
I've noticed that sometimes the Wazuh API service inside Wazuh container is stopped.

Just by sshing inside and doing `service wazuh-api restart` fixes it, but I do wonder, why does that happen?

Regards.

**Comment by manuasir** [comment] 2019-04-17 12:57
Hi @havidarou ,

Thank you for reporting this. I didn't get able to reproduce this issue yet, so I'll let you know when we find anything.

Cheers

**Comment by manuasir** [comment] 2019-04-26 13:43
I still didn't be able to reproduce this behavior. If you could provide some details in order to reproduce your very exact environment, it'd be helpful.

Thanks!

**Comment by bermannoah** [comment] 2020-05-04 13:34
Hi there, I've also been able to duplicate this issue. Can you let me know what information would be useful in terms of debugging? It occurs for me when the container is rebooted completely (e.g. as part of a docker-compose restart) but other than that there doesn't seem to be a consistent root cause. Let me know what I can look into and I'll see if I can get some info. :)

**Comment by manuasir** [comment] 2020-05-04 14:52
Hello @bermannoah ,

Could you please share with us here the specific steps to reproduce this behavior? I wasn't able to get it replicated yet. I'd check logs like:
- `/var/ossec/logs/ossec.log`
- `/var/ossec/logs/api.log`

I'll be waiting for your feedback.

**Comment by bermannoah** [comment] 2020-05-04 15:14
@manuasir Ahh, hold up, I might have an idea. I think the API was creating a new key/cert every time it booted up, since I didn't have one stored in my custom config directory. I've added one and now I don't have this issue. @havidarou by any chance was this the same case on your end?

**Comment by harshil-darji** [comment] 2020-05-29 07:29
I am facing the same issue that shows Wazuh API seems to be down. I tried doing `service wazuh-api restart` which shows Wazuh API running. Then after doing `service wazuh-api status`, it shows that it is stopped. These are the commands along with the outputs.

`root@wazuh-manager:/# service wazuh-api restart
WAZUH-API is not running.
WAZUH-API started.
root@wazuh-manager:/# service wazuh-api status
WAZUH-API is stopped.

 

Last 20 log entries:
WazuhAPI 2020-05-28 06:44:58 foo: [::ffff:172.20.0.6] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:01 foo: [::ffff:172.20.0.6] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:02 foo: [::ffff:172.20.0.6] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:04 foo: [::ffff:172.20.0.6] GET /cluster/nodes? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:04 foo: [::ffff:172.20.0.6] GET /cluster/node? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:05 foo: [::ffff:172.20.0.6] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:06 foo: [::ffff:172.20.0.6] GET /agents/?offset=0&limit=500&q=id!%3D000 - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:06 foo: [::ffff:172.20.0.6] GET /version? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:09 foo: [::ffff:172.20.0.6] GET /cluster/nodes? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:09 foo: [::ffff:172.20.0.6] GET /cluster/config? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:09 foo: [::ffff:172.20.0.6] GET /cluster/healthcheck? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:09 foo: [::ffff:172.20.0.6] GET /agents/?limit=1 - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:22 foo: [::ffff:172.20.0.6] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:25 foo: [::ffff:172.20.0.6] GET /summary/agents? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:26 foo: [::ffff:172.20.0.6] GET /version? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:27 foo: [::ffff:172.20.0.6] GET /agents/?limit=500&offset=0&sort=id - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:27 foo: [::ffff:172.20.0.6] GET /agents/000/config/auth/auth? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:32 foo: [::ffff:172.20.0.6] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:35 foo: [::ffff:172.20.0.6] GET /agents/007? - 200 - error: '0'.
WazuhAPI 2020-05-28 06:45:38 foo: [::ffff:172.20.0.6] GET /agents/groups? - 200 - error: '0'.

 

Full log: /var/ossec/logs/api.log`

**Comment by manuasir** [comment] 2020-11-03 14:44
Closing due to the Wazuh API is now integrated along with the Wazuh manager in our Docker image in v4.0

**Closed by manuasir** 2020-11-03 14:44 UTC
Labels: operations, priority/medium, status/on-hold, type/bug
