### ISSUE TITLE
Mounting over /var/ossec/etc in Wazuh container can break Kibana

### ISSUE THREAD

**Issue by jplangford** [wazuh/wazuh-docker#566] opened 2022-01-17 14:56 UTC
When standing up a new cluster along the same lines as wazuh-docker/production-cluster.yml you may see that Kibana never starts up once you start changing container mounts around.

In my case, this was because I mounted a local volume over the wazuh container's /var/ossec/etc folder and the /var/ossec/etc/shared/ar.conf file was then missing.

Here are my wazuh container mounts:

    sudo docker inspect -f '{{ .Mounts }}' f8b264b2e8ad
    [{bind  /data/wazuh/ossec_active_response /var/ossec/active-response/bin  rw true rprivate} {bind  /data/wazuh/filebeat_etc /etc/filebeat  rw true rprivate} {bind  /data/wazuh/filebeat_log /var/log/filebeat  rw true rprivate} {bind  /data/wazuh/ossec_api_configuration /var/ossec/api/configuration  rw true rprivate} {bind  /data/wazuh/ossec_queue /var/ossec/queue  rw true rprivate} {bind  /data/wazuh/ossec_var_multigroups /var/ossec/var/multigroups  rw true rprivate} {bind  /data/wazuh/filebeat_var /var/lib/filebeat  rw true rprivate} {bind  /data/wazuh/ossec_logs /var/ossec/logs  rw true rprivate} {bind  /data/wazuh/ossec_integrations /var/ossec/integrations  rw true rprivate} {bind  /data/wazuh/ossec_wodles /var/ossec/wodles  rw true rprivate} {bind  /data/wazuh/ossec_etc /var/ossec/etc  rw true rprivate} {bind  /data/wazuh/ossec_agentless /var/ossec/agentless  rw true rprivate}]

The Kibana docker log output just sticks on:

    Wazuh alerts template not loaded - sleeping.
    Wazuh alerts template not loaded - sleeping.
    Wazuh alerts template not loaded - sleeping.

And from the wazuh container docker log I get:

    sudo docker logs 97d5204ae209
    [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
    [s6-init] ensuring user provided files have correct perms...exited 0.
    [fix-attrs.d] applying ownership & permissions fixes...
    [fix-attrs.d] done.
    [cont-init.d] executing container initialization scripts...
    [cont-init.d] 0-wazuh-init: executing... 
    The path /var/ossec/api/configuration is already mounted
    The path /var/ossec/etc is already mounted
    The path /var/ossec/logs is already mounted
    The path /var/ossec/queue is already mounted
    The path /var/ossec/agentless is already mounted
    Installing /var/ossec/var/multigroups
    The path /var/ossec/integrations is already mounted
    The path /var/ossec/active-response/bin is already mounted
    The path /var/ossec/wodles is already mounted
    The path /etc/filebeat is already mounted
    Updating /var/ossec/etc/internal_options.conf
    Updating /var/ossec/integrations/pagerduty
    Updating /var/ossec/integrations/slack
    Updating /var/ossec/integrations/slack.py
    Updating /var/ossec/integrations/virustotal
    Updating /var/ossec/integrations/virustotal.py
    Updating /var/ossec/active-response/bin/default-firewall-drop
    Updating /var/ossec/active-response/bin/disable-account
    Updating /var/ossec/active-response/bin/firewalld-drop
    Updating /var/ossec/active-response/bin/firewall-drop
    Updating /var/ossec/active-response/bin/host-deny
    Updating /var/ossec/active-response/bin/ip-customblock
    Updating /var/ossec/active-response/bin/ipfw
    Updating /var/ossec/active-response/bin/kaspersky.py
    Updating /var/ossec/active-response/bin/kaspersky
    Updating /var/ossec/active-response/bin/npf
    Updating /var/ossec/active-response/bin/wazuh-slack
    Updating /var/ossec/active-response/bin/pf
    Updating /var/ossec/active-response/bin/restart-wazuh
    Updating /var/ossec/active-response/bin/restart.sh
    Updating /var/ossec/active-response/bin/route-null
    Updating /var/ossec/agentless/sshlogin.exp
    Updating /var/ossec/agentless/ssh_pixconfig_diff
    Updating /var/ossec/agentless/ssh_asa-fwsmconfig_diff
    Updating /var/ossec/agentless/ssh_integrity_check_bsd
    Updating /var/ossec/agentless/main.exp
    Updating /var/ossec/agentless/su.exp
    Updating /var/ossec/agentless/ssh_integrity_check_linux
    Updating /var/ossec/agentless/register_host.sh
    Updating /var/ossec/agentless/ssh_generic_diff
    Updating /var/ossec/agentless/ssh_foundry_diff
    Updating /var/ossec/agentless/ssh_nopass.exp
    Updating /var/ossec/agentless/ssh.exp
    Updating /var/ossec/wodles/aws/aws-s3
    Updating /var/ossec/wodles/aws/aws-s3.py
    Updating /var/ossec/wodles/azure/azure-logs
    Updating /var/ossec/wodles/azure/azure-logs.py
    Updating /var/ossec/wodles/docker/DockerListener
    Updating /var/ossec/wodles/docker/DockerListener.py
    Updating /var/ossec/wodles/gcloud/gcloud
    Updating /var/ossec/wodles/gcloud/gcloud.py
    Updating /var/ossec/wodles/gcloud/integration.py
    Updating /var/ossec/wodles/gcloud/tools.py
    Updating /var/ossec/wodles/utils.py
    No Wazuh configuration files to mount...
    [cont-init.d] 0-wazuh-init: exited 0.
    [cont-init.d] 1-config-filebeat: executing... 
    Customize Elasticsearch ouput IP
    Configuring username.
    Configuring password.
    Configuring SSL verification mode.
    [cont-init.d] 1-config-filebeat: exited 0.
    [cont-init.d] 2-manager: executing... 
    2022/01/17 14:04:37 wazuh-analysisd: ERROR: (1103): Could not open file 'etc/shared/ar.conf' due to [(2)-(No such file or directory)].
    2022/01/17 14:04:37 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
    wazuh-analysisd: Configuration error. Exiting
    [cont-init.d] 2-manager: exited 1.
    [cont-init.d] done.
    [services.d] starting services
    starting Filebeat
    2022/01/17 13:42:16 wazuh-analysisd: ERROR: (1103): Could not open file 'etc/shared/ar.conf' due to [(2)-(No such file or directory)].
    2022/01/17 13:42:16 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
    2022/01/17 13:52:20 wazuh-analysisd: ERROR: (1103): Could not open file 'etc/shared/ar.conf' due to [(2)-(No such file or directory)].
    2022/01/17 13:52:20 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
    2022/01/17 13:53:40 wazuh-analysisd: ERROR: (1103): Could not open file 'etc/shared/ar.conf' due to [(2)-(No such file or directory)].
    2022/01/17 13:53:40 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
    2022/01/17 14:01:25 wazuh-analysisd: ERROR: (1103): Could not open file 'etc/shared/ar.conf' due to [(2)-(No such file or directory)].
    2022/01/17 14:01:25 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
    2022/01/17 14:04:37 wazuh-analysisd: ERROR: (1103): Could not open file 'etc/shared/ar.conf' due to [(2)-(No such file or directory)].
    2022/01/17 14:04:37 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
    [services.d] done.

ps output in the container shows that there are no ossec processes running:

    sudo docker exec 97d5204ae209 ps -ef
    UID          PID    PPID  C STIME TTY          TIME CMD
    root           1       0  0 14:04 ?        00:00:00 s6-svscan -t0 /var/run/s6/services
    root          35       1  0 14:04 ?        00:00:00 s6-supervise s6-fdholderd
    root         379       1  0 14:04 ?        00:00:00 s6-supervise ossec-logs
    root         380       1  0 14:04 ?        00:00:00 s6-supervise filebeat
    root         382     379  0 14:04 ?        00:00:00 tail -f /var/ossec/logs/ossec.log
    root         383     380  0 14:04 ?        00:00:00 /usr/share/filebeat/bin/filebeat -e -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat
    root         418       0  2 14:07 ?        00:00:00 ps -ef

However, creating the /data/wazuh/ossec_etc/shared directory on the host system and adding the contents of the default ar.conf to /data/wazuh/ossec_etc/shared/ar.conf allows everything to start up normally. I copied it from another instance of the container (without the mounts).

This took me a long time to work out as I was convinced that filebeat was the problem (and it wasn't).

**Comment by vcerenu** [comment] 2022-01-24 19:04
Hello @jplangford jplangford 

I was trying to reproduce the error but I had no problems when I mounted the _/var/ossec/etc_ directory on the disk.

This is the volume configuration in the **production-cluster.yaml** script:

```
  wazuh-master:
    image: wazuh/wazuh-odfe:4.2.5
    hostname: wazuh-master
    restart: always
    ports:
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=acme-user
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - ossec-api-configuration:/var/ossec/api/configuration
      - /home/vcerenu/volumenes/etc:/var/ossec/etc
      - ossec-logs:/var/ossec/logs
      - ossec-queue:/var/ossec/queue
      - ossec-var-multigroups:/var/ossec/var/multigroups
      - ossec-integrations:/var/ossec/integrations
      - ossec-active-response:/var/ossec/active-response/bin
      - ossec-agentless:/var/ossec/agentless
      - ossec-wodles:/var/ossec/wodles
      - filebeat-etc:/etc/filebeat
      - filebeat-var:/var/lib/filebeat
      - ./production_cluster/ssl_certs/root-ca.pem:/etc/ssl/root-ca.pem
      - ./production_cluster/ssl_certs/filebeat.pem:/etc/ssl/filebeat.pem
      - ./production_cluster/ssl_certs/filebeat.key:/etc/ssl/filebeat.key
      - ./production_cluster/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
```

I checked inside the container and the shared directory was generated:

```
[root@wazuh-master ~]# cd /var/ossec/etc
[root@wazuh-master etc]# ls -ltr
total 64
-rw-r----- 1 root ossec   118 Oct 27 11:42 localtime
-rw-r----- 1 root ossec   320 Nov 12 19:50 local_internal_options.conf
-rw-r----- 1 root ossec 13348 Nov 12 19:50 internal_options.conf
-rw-r----- 1 root ossec     0 Nov 12 19:50 client.keys
drwxrwx--- 2 root ossec  4096 Nov 15 19:59 rules
drwxrwx--- 2 root ossec  4096 Nov 15 19:59 rootcheck
drwxrwx--- 2 root ossec  4096 Nov 15 19:59 decoders
-rw-r----- 1 root root   1704 Nov 15 19:59 sslmanager.key
-rw-r----- 1 root root   1176 Nov 15 19:59 sslmanager.cert
-rw-rw---- 1 root ossec  9679 Jan 24 18:46 ossec.conf
drwxrwx--- 3 root ossec  4096 Jan 24 18:46 shared
drwxrwx--- 3 root ossec  4096 Jan 24 18:46 lists
[root@wazuh-master etc]# cd shared
[root@wazuh-master shared]# ls -ltr
total 12
-rw-rw---- 1 ossec ossec   76 Nov 12 19:50 agent-template.conf
-rw-r----- 1 root  ossec  228 Jan 24 18:47 ar.conf
drwxrwx--- 2 ossec ossec 4096 Jan 24 18:54 default
[root@wazuh-master shared]# 
```


Could you attach the configuration of the **production-cluster.yaml** script and the container log to verify?

**Comment by bonovoxly** [comment] 2022-01-24 20:49
I ran into this as well, when attempting to mount `authd.pass` in the etc dir. Once I stopped doing that it fixed the issue.

(If the structure is already generated and the Docker volume has the files in there, mounting is fine FYI. It seems to be the initialization maybe? Guessing and sharing though... I did not dig far.)

**Comment by jplangford** [comment] 2022-01-31 10:57
Hi @vcerenu ,

Thanks for taking a look, please find my docker compose file below. The wazuh container logs you can already see above, container id is 97d5204ae209.

`---
version: "3.5"
services:
  wazuh:
    restart: always
    image: wazuh/wazuh-odfe:4.2.5
    volumes:
    - /data/wazuh/ossec_api_configuration:/var/ossec/api/configuration
    - /data/wazuh/ossec_etc:/var/ossec/etc
    - /data/wazuh/ossec_logs:/var/ossec/logs
    - /data/wazuh/ossec_queue:/var/ossec/queue
    - /data/wazuh/ossec_var_multigroups:/var/ossec/var/multigroups
    - /data/wazuh/ossec_integrations:/var/ossec/integrations
    - /data/wazuh/ossec_active_response:/var/ossec/active-response/bin
    - /data/wazuh/ossec_agentless:/var/ossec/agentless
    - /data/wazuh/ossec_wodles:/var/ossec/wodles
    - /data/wazuh/filebeat_etc:/etc/filebeat
    - /data/wazuh/filebeat_var:/var/lib/filebeat
    - /data/wazuh/filebeat_log:/var/log/filebeat
    ports:
    - 1514:1514
    - 1515:1515
    - 55000:55000
    environment:
    - "ELASTICSEARCH_URL=https://elasticsearch:9200"
    - "ELASTIC_USERNAME=admin"
    - "ELASTIC_PASSWORD=admin"
    - "FILEBEAT_SSL_VERIFICATION_MODE=none"
    hostname: wazuh-manager
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  elasticsearch:
    restart: always
    image: amazon/opendistro-for-elasticsearch:1.13.3
    volumes:
    - /data/elasticsearch/config:/usr/share/elasticsearch/config
    - /data/elasticsearch/index:/usr/share/elasticsearch/data
    - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
    - 9200:9200
    environment:
    - "discovery.type=single-node"
    - "cluster.name=wazuh-cluster"
    - "network.host=0.0.0.0"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "bootstrap.memory_lock=true"
    hostname: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  kibana:
    restart: always
    image: wazuh/wazuh-kibana-odfe:4.2.5
    volumes:
    - /data/kibana/config:/usr/share/kibana/config
    ports:
    - 443:5601
    environment:
    - "ELASTICSEARCH_USERNAME=admin"
    - "ELASTICSEARCH_PASSWORD=admin"
    - "SERVER_SSL_ENABLED=true"
    - "SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/kibana.crt"
    - "SERVER_SSL_KEY=/usr/share/kibana/config/kibana.key"
    depends_on:
    - elasticsearch
    hostname: kibana
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
`

**Comment by vcerenu** [comment] 2022-01-31 18:26
Hello

I was checking your configuration and I don't see what can cause the error, except that the volume was already created and contains files or some Docker configuration that we are not seeing. I did a deploy with your yaml and have had no errors:

```
$ cat docker-compose.yml 
# Wazuh App Copyright (C) 2021 Wazuh Inc. (License GPLv2)
version: "3.5"
services:
  wazuh:
    restart: always
    image: wazuh/wazuh-odfe:4.2.5
    volumes:
    - /data/wazuh/ossec_api_configuration:/var/ossec/api/configuration
    - /data/wazuh/ossec_etc:/var/ossec/etc
    - /data/wazuh/ossec_logs:/var/ossec/logs
    - /data/wazuh/ossec_queue:/var/ossec/queue
    - /data/wazuh/ossec_var_multigroups:/var/ossec/var/multigroups
    - /data/wazuh/ossec_integrations:/var/ossec/integrations
    - /data/wazuh/ossec_active_response:/var/ossec/active-response/bin
    - /data/wazuh/ossec_agentless:/var/ossec/agentless
    - /data/wazuh/ossec_wodles:/var/ossec/wodles
    - /data/wazuh/filebeat_etc:/etc/filebeat
    - /data/wazuh/filebeat_var:/var/lib/filebeat
    - /data/wazuh/filebeat_log:/var/log/filebeat
    ports:
    - 1514:1514
    - 1515:1515
    - 55000:55000
    environment:
    - "ELASTICSEARCH_URL=https://elasticsearch:9200"
    - "ELASTIC_USERNAME=admin"
    - "ELASTIC_PASSWORD=admin"
    - "FILEBEAT_SSL_VERIFICATION_MODE=none"
    hostname: wazuh-manager
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  elasticsearch:
    restart: always
    image: amazon/opendistro-for-elasticsearch:1.13.3
    volumes:
    - /data/elasticsearch/config:/usr/share/elasticsearch/config
    - /data/elasticsearch/index:/usr/share/elasticsearch/data
    - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
    - 9200:9200
    environment:
    - "discovery.type=single-node"
    - "cluster.name=wazuh-cluster"
    - "network.host=0.0.0.0"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "bootstrap.memory_lock=true"
    hostname: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  kibana:
    restart: always
    image: wazuh/wazuh-kibana-odfe:4.2.5
    volumes:
    - /data/kibana/config:/usr/share/kibana/config
    ports:
    - 443:5601
    environment:
    - "ELASTICSEARCH_USERNAME=admin"
    - "ELASTICSEARCH_PASSWORD=admin"
    - "SERVER_SSL_ENABLED=true"
    - "SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/kibana.crt"
    - "SERVER_SSL_KEY=/usr/share/kibana/config/kibana.key"
    depends_on:
    - elasticsearch
    hostname: kibana
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
$ docker-compose up -d
Creating wazuh-docker_wazuh_1         ... done
Creating wazuh-docker_elasticsearch_1 ... done
Creating wazuh-docker_kibana_1        ... done
$ docker exec -it wazuh-docker_wazuh_1 bash
[root@wazuh-manager /]# ls -ltr /var/ossec/etc/shared/
total 12
-rw-rw---- 1 ossec ossec   76 Nov 12 19:50 agent-template.conf
-rw-r----- 1 root  ossec  228 Jan 31 15:51 ar.conf
drwxrwx--- 2 ossec ossec 4096 Jan 31 15:52 default
[root@wazuh-manager /]# exit
exit
$ 
```

I ask you if you can try to perform a deployment with the production-cluster.yml script, you have to follow some steps described in the documentation:
https://documentation.wazuh.com/current/docker/wazuh-container.html#production-deployment

**Comment by alberpilot** [comment] 2022-03-23 07:27
Hello all

I proceed to close this issue. Please don't hesitate to open again if you need further assistance. 

Regards
Alberto R

**Closed by alberpilot** 2022-03-23 07:27 UTC
Labels: community, cicd-tracked
