### ISSUE TITLE
Consider auto-restarting worker containers once they have been synchronized

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh-docker#550] opened 2021-11-11 17:57 UTC
Hello team,

In Kubernetes environments where worker pods can be automatically deployed, a worker container should be automatically restarted after a synchronization so custom rules and decoders can take place.

## Description

Wazuh managers need to be restarted in order to new rules and decoders take place after that have been added. In some environments, workers are automatically deployed and they should not need additional interaction to work properly.

## Possible solutions

We should have an init script to automatically restart the `wazuh-manager` service if the container is a `worker` inside a cluster.

This restart should only take place the first time the container is started.

Regards,
Franco Hielpos

**Comment by vcerenu** [comment] 2021-12-15 20:05
Added the function_restart_worker function  inside the _wazuh-odfe/config/etc/2-manager_ file , which checks if the Wazuh Manager cluster node is a worker and restarts the Manager services if It's true

```
function_restart_worker() {
  # Extract what type of node is configured in the ossec.conf file
  node_type=`grep node_type /var/ossec/etc/ossec.conf | sed 's/<\/\?[^>]\+>//g'`
  # If the node type is Worker, the wazuh-manager service is restarted for correct registration in the cluster
  if [ $node_type == "worker" ] 
  then
    /var/ossec/bin/wazuh-control restart
  fi
}
```

**Comment by alberpilot** [comment] 2021-12-16 18:07
I proceed to close this issue. Although it works, the problem is not at the deployment level, the Cluster nodes must be able to hot reload pushed configurations, so we will open a new issue in the main repository.
Regards,
Alberto R

**Closed by alberpilot** 2021-12-16 18:07 UTC
Labels: operations, cicd-tracked
