### ISSUE TITLE
Apply Wazuh daemons name changing to wazuh-docker

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-docker#421] opened 2020-12-14 17:06 UTC
## Description
Hello team. 

According to the changes proposed at wazuh/wazuh#6741, the following daemons will be renamed or totally removed from new Wazuh installations.

- Unix:
  - `ossec-agentd` -> `wazuh-agentd`
  - `ossec-agentlessd` -> `wazuh-agentlessd`
  - `ossec-analysisd` -> `wazuh-analysisd`
  - `ossec-authd` -> `wazuh-authd`
  - `ossec-csyslogd` -> `wazuh-csyslogd`
  - `ossec-dbd` -> `wazuh-dbd`
  - `ossec-execd` -> `wazuh-execd`
  - `ossec-integratord` -> `wazuh-integratord`
  - `ossec-logcollector` -> `wazuh-logcollector`
  - `ossec-maild` -> `wazuh-maild`
  - `ossec-monitord` -> `wazuh-monitord`
  - `ossec-remoted` -> `wazuh-remoted`
  - `ossec-reportd` -> `wazuh-reportd`
  - `ossec-syscheckd` -> `wazuh-syscheckd`

- Windows:
  - `ossec-agent.exe` -> `wazuh-agent.exe`
  - `ossec-agent-eventchannel.exe` -> `wazuh-agent-eventchannel.exe`
  - `ossec-rootcheck.exe` -> deprecated

I saw references to these daemons in this repo. Please, update these references according to the proposed renaming.

**Comment by xr09** [comment] 2020-12-14 17:28
Duplicate of #418?

**Comment by xr09** [comment] 2020-12-15 18:53
Solved by #422

**Closed by xr09** 2020-12-15 18:53 UTC
Labels: type/maintenance
