### ISSUE TITLE
Cannot create container for service elasticsearch

### ISSUE THREAD

**Issue by marcRBD** [wazuh/wazuh-docker#6] opened 2017-04-06 12:04 UTC
hello
i'm not familiar with docker, but does the elastic container misses in files ?

wazuh-docker-master# docker-compose up
Creating wazuhdockermaster_elasticsearch_1

ERROR: for elasticsearch  Cannot create container for service elasticsearch: b'invalid port specification: "None"'
ERROR: Encountered errors while bringing up the project.

Thanks

**Comment by jlruizmlg** [comment] 2017-04-06 13:35
Hi @marcRBD seems like you miss something in the configuration, can you share your docker-compose.yml to take a look?
Thanks!

**Comment by marcRBD** [comment] 2017-04-06 13:39
hi 

i not change anything:
file
-rw-r--r--  1 root root  1456 mars  31 14:06 docker-compose.yml
drwxr-xr-x  2 root root  4096 mars  31 14:06 images
drwxr-xr-x  3 root root  4096 mars  31 14:06 kibana
drwxr-xr-x  3 root root  4096 mars  31 14:06 logstash
-rw-r--r--  1 root root 17454 mars  31 14:06 README.md
drwxr-xr-x  3 root root  4096 avril  6 13:53 wazuh


[docker-compose.zip](https://github.com/wazuh/wazuh-docker/files/902697/docker-compose.zip)

thanks

**Comment by jlruizmlg** [comment] 2017-04-06 13:47
@marcRBD do you  have any other service running in the port 9200 or 9300?

Try to use the next docker-compose.yml, the only changes is remove the port section

```
version: '2'

services:
  wazuh:
    image: wazuh/wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514/udp:1514/udp"
      - "1515:1515"
      - "514/udp:514/udp"
      - "55000:55000"
    networks:
        - docker_elk
#    volumes:
#      - my-path:/var/ossec/data
#      - my-path:/etc/postfix
    depends_on:
      - elasticsearch
  logstash:
    image: wazuh/wazuh-logstash
    hostname: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
#    volumes:
#      - my-path:/etc/logstash/conf.d
    links:
     - kibana
     - elasticsearch
    ports:
      - "5000:5000"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  elasticsearch:
    image: elasticsearch:5.2.2
    hostname: elasticsearch
    restart: always
    command: elasticsearch -E node.name="node-1" -E cluster.name="wazuh" -E network.host=0.0.0.0
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
#    volumes:
#      - my-path:/usr/share/elasticsearch/data
    networks:
        - docker_elk
  kibana:
    image: wazuh/wazuh-kibana
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
        - docker_elk
    depends_on:
      - elasticsearch
    entrypoint: sh wait-for-it.sh elasticsearch

networks:
  docker_elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
```

**Comment by marcRBD** [comment] 2017-04-06 14:10
it is fresh install with nothing, on a debian jessie

root@debian-jessie:~/wazuh-docker-master# netstat -an  | grep 9200
root@debian-jessie:~/wazuh-docker-master#

telnet localhost 9200
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused


same problem with the fresh install and your docker-compose command

Status: Downloaded newer image for elasticsearch:5.3.0
Creating wazuhdockermaster_elasticsearch_1

ERROR: for elasticsearch  Cannot create container for service elasticsearch: b'invalid port specification: "None"'
ERROR: Encountered errors while bringing up the project.

Same error with or without the elk ports remove in docker-compose.yml

as i miss something ?

i download the master.zip, unzip and launch 

docker-compose stop
docker-compose rm
docker-compose up

**Comment by marcRBD** [comment] 2017-04-06 14:21
with your docker-compose.yml

Pulling elasticsearch (elasticsearch:5.3.3)...
ERROR: manifest for elasticsearch:5.3.3 not found

**Comment by jlruizmlg** [comment] 2017-04-06 14:28
@marcRBD i fix that you are right is 5.3.0, not 5.3.3

On the other hand, can you give me your docker and docker-compose version??

**Comment by marcRBD** [comment] 2017-04-06 14:37
dpkg -l | grep docker
ii  **docker-ce                             17.03.1~ce-0~debian-jessie**           amd64        Docker: the open-source application container engine

 docker-compose -v
**docker-compose version 1.12.0, build b31ff33**

as i need to do anything else ?

**Comment by marcRBD** [comment] 2017-04-06 14:42
so my version is wrong :(
Install Docker-compose version >= 1.6.

sorry, just follow the intrusction on docker website and i was thinking it was the last good one

**Comment by jlruizmlg** [comment] 2017-04-06 15:45
@marcRBD i cannot reproduce your issue with the same versions than you, do you have more containers running?

```
docker ps -a
```

my versions
```
root@debian:~# docker --version
Docker version 17.03.1-ce, build c6d412e
root@debian:~# docker-compose --version
docker-compose version 1.12.0, build b31ff33
root@debian:~#
```
You can also run the following command again, but the docker system prune will remove from your system all unused data (networks, images, etc) so be careful with this command.

```
docker-compose stop
docker-compose rm
docker system prune
docker-compose up
```

**Comment by marcRBD** [comment] 2017-04-07 07:30
hi

docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                    PORTS               NAMES
94048dba501d        hello-world         "/hello"            21 hours ago        Exited (0) 21 hours ago                       nifty_lamport


docker stop 94048dba501d
docker rm 94048dba501d

docker-compose stop
docker-compose rm
 docker system prune
WARNING! This will remove:
        - all stopped containers
        - all volumes not used by at least one container
        - all networks not used by at least one container
        - all dangling images
Are you sure you want to continue? [y/N] y
Deleted Volumes:
135f36a7563fd10f7040046d8a455c318c8179b6620a3ed09d6849ba44bc5907

Deleted Networks:
wazuhdockermaster_docker_elk

Total reclaimed space: 0 B

docker-compose up

Creating network "wazuhdockermaster_docker_elk" with driver "bridge"
Pulling elasticsearch (elasticsearch:5.3.3)...
ERROR: manifest for elasticsearch:5.3.3 not found

very strange !

**Comment by jlruizmlg** [comment] 2017-04-07 07:45
Don't use 5.3.3 was a typo is 5.3.0 in the docker-compose.yml

Regards
-----------------------
Jose Luis Ruiz
Wazuh Inc.
jose@wazuh.com

**Comment by marcRBD** [comment] 2017-04-07 07:52
but in my docker-compose
this is   "elasticsearch:
    image: elasticsearch:5.3.0"

some sort of a bug ?

try again:

Creating network "wazuhdockermaster_docker_elk" with driver "bridge"
Creating wazuhdockermaster_elasticsearch_1

ERROR: for elasticsearch  Cannot create container for service elasticsearch: b'invalid port specification: "None"'
ERROR: Encountered errors while bringing up the project.

**Comment by marcRBD** [comment] 2017-04-07 08:15
i take this file for my docker-compose.yml
and it is going well for now!

https://github.com/wazuh/wazuh-docker/blob/ad8babfe353b56fc50afc07a0104f1883f5d4ee8/docker-compose-build.yml

i'm not expert with github and i was thiking the change was commit in master .
More information at the end of the installation

**Comment by marcRBD** [comment] 2017-04-07 08:20
there is some sort of a misunderstanding, and i don't know where

ERROR: for kibana  Cannot create container for service kibana: b'invalid port specification: "None"'

ERROR: for wazuh  Cannot create container for service wazuh: b'invalid port specification: "None"'
ERROR: Encountered errors while bringing up the project.

**Comment by marcRBD** [comment] 2017-04-07 09:54
works way better on centos 7

> except: Could not resolve host: elasticsearch

where do i change a host file and for what ?
thanks

**Comment by jlruizmlg** [comment] 2017-04-07 16:57
Hi @marcRBD, docker-compose update the docker DNS, if you are running the docker-compose.yml the and you have this line in your compose https://github.com/wazuh/wazuh-docker/blob/master/docker-compose.yml#L40 with the container name should work.

**Comment by marcRBD** [comment] 2017-04-10 09:28
hi @jlruizmlg 

it is good in the file

  elasticsearch:
    image: elasticsearch:5.3.0
    hostname: elasticsearch

but still got the error !

**Comment by marcRBD** [comment] 2017-04-10 09:56
the problem must be elastic component

kibana_1         |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: elasticsearch
kibana_1         | Elastic is unavailable - sleeping

thanks

**Comment by marcRBD** [comment] 2017-04-10 11:54
it works now on centos, thanks for the help
do you want to close or do you want i recheck on debian it was the same problem ?
it needs more memory and i didn't saw the requirements beforce launching

**Comment by jlruizmlg** [comment] 2017-04-10 17:07
Hi @marcRBD nice news!! i will close the issue but please update with any extra information!

**Closed by jlruizmlg** 2017-04-10 17:07 UTC
