### ISSUE TITLE
Error in generate-indexer-certs

### ISSUE THREAD

**Issue by SYRTI** [wazuh/wazuh-docker#728] opened 2022-10-14 11:12 UTC
Cant generate the Certificates with docker-compose -f generate-indexer-certs.yml run --rm generator
because the image image: wazuh/wazuh-certs-generator:0.0.1
seems to point at PACKAGES_URL=https://packages.wazuh.com/4.3/ which throws this message:
Cert tool does not exist in any bucket
ERROR: certificates were not created

**Comment by maxferrario-msf** [comment] 2022-10-20 10:25
I have the same error when I run the command to generate the certificates

~/wazuh-docker/single-node$ sudo docker-compose -f generate-indexer-certs.yml run --rm generator
/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Creating network "single-node_default" with the default driver
Pulling generator (wazuh/wazuh-certs-generator:0.0.1)...
0.0.1: Pulling from wazuh/wazuh-certs-generator
d7bfe07ed847: Pull complete
a6023cfa8265: Pull complete
6135753eefe9: Pull complete
9aaf0dae5d3f: Pull complete
Digest: sha256:6fc929d58d01b789d4a19c5da476c78cc267c0af07d1b22227ccae49acb084dc
Status: Downloaded newer image for wazuh/wazuh-certs-generator:0.0.1
Creating single-node_generator_run ... done

Cert tool does not exist in any bucket
ERROR: certificates were not created
ERROR: 1

**Comment by rauldpm** [comment] 2022-10-25 15:18
Closed for being a duplicate of: https://github.com/wazuh/wazuh-docker/issues/733

**Closed by rauldpm** 2022-10-25 15:18 UTC
