### ISSUE TITLE
PagerDuty integration does not work

### ISSUE THREAD

**Issue by slawekgl79** [wazuh/wazuh-docker#290] opened 2020-01-07 15:48 UTC
When PagerDuty integration is configured, Wazuh is not able to send any alarms.

In docker log:
`/var/ossec/integrations/pagerduty: 82: /var/ossec/integrations/pagerduty: Bad substitution`

The problem can be solved by changing the shell in the pagerduty scripts shebang-line (which would be safer) from /bin/sh to /bin/bash OR by changing the default sh from dash to bash.

**Comment by jm404** [comment] 2020-01-08 14:02
Hi @slawekgl79,

I managed to reproduce your case and as you stated changing the shebang to `bash` fixes it.

It seems to be an error in the integration script which affects all kind of installations:https://github.com/wazuh/wazuh/issues/3639

We will investigate this 

Thanks for reporting it!

Best regards,

Jose

**Comment by jm404** [comment] 2020-03-30 18:06
Hi @slawekgl79 ,

I'm closing this as you managed to fix it and a related issue has been opened in `wazuh/wazuh` repository https://github.com/wazuh/wazuh/pull/4641

Feel free to open a new one if you need it

Best regards,

Jose

**Closed by jm404** 2020-03-30 18:06 UTC
Labels: community
