### ISSUE TITLE
missing wazuh-agent index no data showing in wazuh

### ISSUE THREAD

**Issue by bluenevus** [wazuh/wazuh-docker#122] opened 2019-02-23 18:42 UTC
Data is not showing in wazuh though its connected to 12 agents.  Looking at Index Management below
![image](https://user-images.githubusercontent.com/3675043/53290346-95c39b00-3770-11e9-8076-faf1e0d83a0d.png)

there is no wazuh-alerts index.  I must have blown away this image and recreate it a number of times without any success.  I have filebeat on the hosts and its sending data.  I also have suricata for which filebeat is sending the data.

**Comment by RANGERBEE** [comment] 2019-02-23 18:46
It's your agent config, restart your agent after setting your config properly and get rid of all those other forwarders

⁣Get BlueMail for Android ​

**Comment by bluenevus** [comment] 2019-02-23 18:47
Just an update is that even though it can't find it in index management, it does show up as an index pattern

![image](https://user-images.githubusercontent.com/3675043/53290409-885ae080-3771-11e9-8ef7-04a8de4c4f44.png)

**Comment by bluenevus** [comment] 2019-02-23 18:57
are you talking 
/var/ossec/etc/ossec.conf
or 
/var/ossec/etc/shared/agent.conf

for the ossec conf the only setting I changed was the address to go to the right server
for agent.conf  that pretty much blank  says share configuration here but no config

**Comment by RANGERBEE** [comment] 2019-02-23 19:11
Config for agent on the host..  You probably have a msconfig. Also poke a hole on host for udp/1514 to your manager...  the agent config states what logs to monitor, port to use and manager ip.  I seem to remember that agents also must match manager version.  Check agent logs on sending host it will tell you where hosed up.



⁣Get BlueMail for Android ​

**Comment by bluenevus** [comment] 2019-02-23 19:29
1514 is definitely open firewall-cmd –list-all shows that and 514 udp

Agents match the manager version.  Each agent shows its connected.

The ports are definitely exposed on docker also.
0.0.0.0:1514  1514/udp
0.0.0.0:1515  1515/tcp
0.0.0.0:514  514/udp
0.0.0.0:55000  55000/tcp

Its trying to connect to the server on 1514 udp but then gives this error ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused on the agent side

On the host side this is the error message

2019/02/23 19:09:57 ossec-remoted: INFO: Started (pid: 218).
2019/02/23 19:09:57 ossec-monitord: INFO: Started (pid: 247).
2019/02/23 19:10:12 ossec-syscheckd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2019/02/23 19:10:12 rootcheck: CRITICAL: (1211): Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
2019/02/23 19:10:12 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/02/23 19:10:12 ossec-remoted: CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
2019/02/23 19:10:12 ossec-logcollector: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2019/02/23 19:10:12 ossec-logcollector: CRITICAL: (1211): Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
2019/02/23 19:10:22 ossec-monitord: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/02/23 19:10:22 ossec-monitord: CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..

I appreciate your patience as I’m really at a loss on what configuration I’m missing causing this
--- vr, Frank

**Comment by bluenevus** [comment] 2019-02-23 19:43
I also did this based on documentation from ossec on this issue regarding the queue but no change

What does “1210 - Queue not accessible?” mean?
Check queue/ossec/queue
If you have logs similar to the following in /var/ossec/queue/ossec/queue:

2008/04/29 15:40:39 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2008/04/29 15:40:39 ossec-rootcheck(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2008/04/29 15:40:45 ossec-logcollector(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2008/04/29 15:40:45 ossec-logcollector(1211): ERROR: Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
2008/04/29 15:41:00 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2008/04/29 15:41:00 ossec-rootcheck(1211): ERROR: Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
It means that ossec-analysisd is not running for some reason.

The main reasons for this to happen are:

ossec-analysisd didn’t start properly. Look at the logs for any error from it.
ossec-analysisd didn’t start at all. There is a bug in the init scripts that during system reboot, it may not start if the PID is already in use (we are working to fix it).
ossec-analysisd cannot access /queue/fts/fts-queue. Look for the error message ossec-analysisd(1103): ERROR: Unable to open file '/queue/fts/fts-queue'. This can be fixed by ensuring that the ossec user owns /var/ossec/queue/fts/fts-queue.
How to fix it:

Stop OSSEC and start it back again:

# /var/ossec/bin/ossec-control stop
(you can also check at /var/ossec/var/run that there is not PID file in there)
# /var/ossec/bin/ossec-control start

**Comment by bluenevus** [comment] 2019-02-23 19:45
well I should say there is a change...no more of the connection error by going into the container and restarting ossec-control however no change in terms of  wazuh-agent index showing in index management and of course adding a new index pattern and still no logs

![image](https://user-images.githubusercontent.com/3675043/53290961-914fb000-3779-11e9-8370-f787a7c3591f.png)

![image](https://user-images.githubusercontent.com/3675043/53290967-a593ad00-3779-11e9-9bbc-77da2d5f2d0a.png)

**Comment by manuasir** [comment] 2019-03-25 11:27
Hello @bluenevus ,

Sorry for the late response. Did you get anything on this issue? Please, let us know if your problem persists and we will try to help.

Cheers

**Comment by bluenevus** [comment] 2019-03-25 13:19
I sort of threw in the towel.  I was hoping to migrate from alien vault. But after many deinstallation, reinstallation, fresh start etc.  I just couldn't get it to work.

--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8245 Boone Blvd, Suite 706  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________

**Comment by manuasir** [comment] 2019-05-02 16:04
Hi @bluenevus ,

I'll try to reproduce your very exact case, so please, attach here the most number of details as you can:

- Host OS and hardware 
- The version of Docker and docker-compose
- The version of the images that you're pulling.
- Your docker-compose or the sequence of docker commands that you're using.

I hope we can solve this

Regards

**Comment by bluenevus** [comment] 2019-05-02 16:11
Centos 7.5-1804

Docker version 18.09.1, build 4c52b90

I would imagine whatever version is here https://github.com/wazuh/wazuh-docker  I don’t have the exact version at the time I stopped using wazuh but we are pretty good about keeping it up to date

I used the compose version that was on GitHub https://github.com/wazuh/wazuh-docker/blob/master/docker-compose.yml

 

 

--- vr, Frank

**Comment by manuasir** [comment] 2019-05-02 18:12
Hi @bluenevus ,

I assume that you were running the full stack (Wazuh manager + ELK) in the same machine. Did you have enough memory? At least, 4 GB of RAM is required. Also, did you set a proper value to the `vm.set_max_map` variable? As described [here](https://documentation.wazuh.com/current/docker/wazuh-container.html#increase-max-map-count-on-your-host-linux), it should be set before running the containers. I'm attaching here the steps that I just followed when trying to reproduce your case in a lab environment, where everything went OK and running correctly. Please, tell me some differences comparing these with your environment that I might have missed:

- Centos 7.5
- docker 18.09
- docker-compose 1.18
--------------
1. Set the `max_map_count` variable:
```
sysctl -w vm.max_map_count=262144
```
2. Clone the repository:

```
git clone https://github.com/wazuh/wazuh-docker
```

3. Pull the images and run the containers with docker-compose:

```
cd wazuh-docker
docker-compose up -d
```

The process takes a while, it should install the Wazuh `v3.8.2` and ELK `v6.7.0`. Browse to `https://localhost` and set the `foo`:`bar` credentials if they didn't change in the `docker-compose.yml` file.

Regards

**Comment by bluenevus** [comment] 2019-05-02 18:22
Yes.  The docker server has 128 gigs of ram and was allocated mostly to the elk stack

Yes. I did the vm.set_max map.

 

Like I said, it would work fine for a day or two then really no data showing and despite the many different ways of trying to get it to work it just didn’t

 

I will say all the servers previously had ossec that was pointed to alienvault.  I uninstalled ossec and installed the wazuh agent so it wasn’t a fresh install.  After struggling for a bit, I went back to ossec to alienvault and it worked.  Maybe something with the original ossec.  I tried to purge the install of ossec.

 

I do have plain ole elk running with filebeat and metricbeat working.  That is working just fine.  I’m mostly using Suricata data as I couldn’t get wazuh to work.

 

--- vr, Frank

**Comment by manuasir** [comment] 2019-05-02 18:53
Hi @bluenevus,

As this seems to be a problem related to your particular environment and your older version of ossec, let me know if we can close this issue here. Otherwise, just let me know if you want to get back to it and I will be glad to help with it.

I also suggest you to join our Slack channel [here](https://wazuh.com/community/join-us-on-slack/), we can check further details of the problem there.

Regards

**Comment by bluenevus** [comment] 2019-05-02 19:37
Sure.  Thanks for the help

 

--- vr, Frank

**Closed** 2019-05-02 19:47 UTC
